name: SonarCloud Analysis

on:
  push:
    branches:
      - main

jobs:
  sonarcloud:
    name: Analyze code with SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install Bundler
        run: gem install bundler

      - name: Install gems
        run: bundle install

      - name: Run tests
        run: bundle exec rspec

      - name: Set up SonarCloud
        uses: sonarsource/sonarcloud-github-action@v3
        with:
          token: ${{ secrets.Tests_github_Actions }}

      - name: Analyze code
        run: |
          sonar-scanner \
            -Dsonar.projectKey=samuelrossato_automation-api-ruby \
            -Dsonar.organization=samuelrossato \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.Tests_github_Actions }}

      - name: Upload results
        uses: sonarsource/sonarcloud-github-action@v3
        with:
          token: ${{ secrets.Tests_github_Actions }}