name: Automation Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Execute automation of API
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install Bundler
        run: gem install bundler

      - name: Install gems
        run: bundle install

      - name: Execute tests
        run: bundle exec rspec
